# site settings
title: Aum Solutions
subtitle: # by html5 up
email: info@aumsolutions.org
description: A responsive site template designed by HTML5 Up<br /> and released under the Creative Commons.
baseurl: "/forty-jekyll-theme" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author:
street_address: 1234 Somewhere Road
city: Nashville
state: TN
zip_code: 55555
country: United States of America
phone: (716) 555-5555

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

permalink: /:title/

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub: https://github.com/andrewbanchich
  GitLab:
  Google-Plus: https://plus.google.com/u/0/+AndrewBanchich
  Instagram:
  LinkedIn: https://www.linkedin.com/in/andrew-banchich-a4ba1195
  Twitter: https://twitter.com/andrewbanchich
  Facebook:
  Slack:

# build settings
markdown: kramdown
plugins:
  - jekyll-paginate-v2

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 

collections:
  blog:
    output: true
    permalink: /blog/:path/

pagination:
  enabled: true
  collection: blog
  per_page: 3
  permalink: '/blog/page/:num/'
  title: ':title - page :num'
  sort_field: 'date'
  sort_reverse: true
  trail:
    before: 2
    after: 2
